[
   {
      "Font":"Creepster",
      "userid":1898371630,
      "TagIdentification":" [ SCRIPTER ] ",
      "ColorTable":[
         255,
         0,
         0
      ],
      "TagText":"Metacalled"
   },
   {
      "Font":"Creepster",
      "userid":713824573,
      "TagIdentification":" [ SCRIPTER ] ",
      "ColorTable":[
         255,
         0,
         0
      ],
      "TagText":"Metacalled"
   },
   {
      "Font":"Creepster",
      "userid":463809410,
      "TagIdentification":" [ VELURITY ] ",
      "ColorTable":[
         255,
         20,
         147
      ],
      "TagText":"Anna"
   },
   {
      "Font":"Creepster",
      "userid":668345977,
      "TagIdentification":" [ AUCESTRE ] ",
      "ColorTable":[
         0,
         0,
         0
      ],
      "TagText":"Eren"
   },
   {
      "Font":"Creepster",
      "userid":139759589,
      "TagIdentification":" [ AUCESTRE ] ",
      "ColorTable":[
         0,
         0,
         0
      ],
      "TagText":"Eren"
   },
   {
      "Font":"Creepster",
      "userid":2261302324,
      "TagIdentification":" [ AUCESTRE ] ",
      "ColorTable":[
         0,
         0,
         0
      ],
      "TagText":"Eren"
   },
   {
      "Font":"Creepster",
      "userid":1762590381,
      "TagIdentification":" [ BITCH ] ",
      "ColorTable":[
         255,
         20,
         147
      ],
      "TagText":"Kate"
   },
   {
      "Font":"Fredoka",
      "userid":147182208,
      "TagIdentification":" [ RETARD GIRL GROUP ] ",
      "ColorTable":[
         74,
         66,
         135
      ],
      "TagText":"Spudaddles"
   },
   {
      "Font":"Fredoka",
      "userid":1083587286,
      "TagIdentification":" [ RETARD GIRL GROUP ] ",
      "ColorTable":[
         74,
         66,
         135
      ],
      "TagText":"Jamie"
   },
   {
      "Font":"Fredoka",
      "userid":454243468,
      "TagIdentification":" [ RETARD GIRL GROUP ] ",
      "ColorTable":[
         74,
         66,
         135
      ],
      "TagText":"Shyanne"
   },
   {
      "Font":"Fredoka",
      "userid":192617749,
      "TagIdentification":" [ RETARD GIRL GROUP ] ",
      "ColorTable":[
         74,
         66,
         135
      ],
      "TagText":"Canan"
   },
   {
      "Font":"Fredoka",
      "userid":846150720,
      "TagIdentification":" [ RETARD GIRL GROUP ] ",
      "ColorTable":[
         74,
         66,
         135
      ],
      "TagText":"Jayda"
   },
   {
      "Font":"Fredoka",
      "userid":899010159,
      "TagIdentification":" [ Retard Girl Group ] ",
      "ColorTable":[
         74,
         66,
         135
      ],
      "TagText":"Jamie / Shyanne"
   },
   {
      "Font":"Creepster",
      "userid":1762400000,
      "TagIdentification":" [ PASSAROUND ] ",
      "ColorTable":[
         74,
         66,
         135
      ],
      "TagText":"KD"
   },
   {
      "Font":"Creepster",
      "userid":92616350,
      "TagIdentification":" [ PASSAROUND ] ",
      "ColorTable":[
         74,
         66,
         135
      ],
      "TagText":"Libby"
   },
   {
      "Font":"Creepster",
      "userid":781004960,
      "TagIdentification":" [ PASSAROUND ] ",
      "ColorTable":[
         74,
         66,
         135
      ],
      "TagText":"Zoe"
   },
   {
      "Font":"Creepster",
      "userid":2258301745,
      "TagIdentification":" [ PASSAROUND ] ",
      "ColorTable":[
         74,
         66,
         135
      ],
      "TagText":"Kim"
   },
   {
      "Font":"Creepster",
      "userid":1410480510,
      "TagIdentification":" [ HELPER ] ",
      "ColorTable":[
         0,
         255,
         0
      ],
      "TagText":"Tester"
   },
   {
      "Font":"Creepster",
      "userid":1440862719,
      "TagIdentification":" [ HELPER ] ",
      "ColorTable":[
         0,
         255,
         0
      ],
      "TagText":"Tester"
   },
   {
      "Font":"Creepster",
      "userid":105183043,
      "TagIdentification":" [ SCRIPTER ] ",
      "ColorTable":[
         20,
         247,
         244
      ],
      "TagText":"Charlie"
   },
   {
      "Font":"Creepster",
      "userid":20165690,
      "TagIdentification":" [ COOL ] ",
      "ColorTable":[
         0,
         255,
         255
      ],
      "TagText":"Shaun"
   },
   {
      "Font":"Creepster",
      "userid":1417460726,
      "TagIdentification":" [ COOL ] ",
      "ColorTable":[
         0,
         255,
         255
      ],
      "TagText":"Fergo"
   },
   {
      "Font":"Creepster",
      "userid":1006384408,
      "TagIdentification":" [ COOL ] ",
      "ColorTable":[
         0,
         255,
         255
      ],
      "TagText":"Updtd"
   },
   {
      "Font":"Creepster",
      "userid":24158945,
      "TagIdentification":" [ COOL ] ",
      "ColorTable":[
         0,
         255,
         255
      ],
      "TagText":"Scottish"
   },
   {
      "Font":"Creepster",
      "userid":94428247,
      "TagIdentification":" [ COOL ] ",
      "ColorTable":[
         0,
         255,
         255
      ],
      "TagText":"Charlotte"
   },
   {
      "Font":"Fredoka",
      "userid":1937111826,
      "TagIdentification":" [ RETARD ] ",
      "ColorTable":[
         255,
         0,
         0
      ],
      "TagText":"SlayesXl"
   },
   {
      "Font":"Fredoka",
      "userid":221789271,
      "TagIdentification":" [ RETARD ] ",
      "ColorTable":[
         255,
         0,
         0
      ],
      "TagText":"Townley"
   },
   {
      "Font":"Fredoka",
      "userid":1578148497,
      "TagIdentification":" [ RETARD ] ",
      "ColorTable":[
         255,
         0,
         0
      ],
      "TagText":"Townley ( SHARED )"
   },
   {
      "Font":"Bangers",
      "userid":355053032,
      "TagIdentification":" [ FANBOY ] ",
      "ColorTable":[
         95,
         12,
         247
      ],
      "TagText":"gohnmane"
   },
   {
      "Font":"Classic",
      "userid":1506101592,
      "TagIdentification":" [ SIMP ] ",
      "ColorTable":[
         255,
         0,
         119
      ],
      "TagText":"c6pl"
   },
   {
      "Font":"Classic",
      "userid":75838249,
      "TagIdentification":" [ SIMP ] ",
      "ColorTable":[
         255,
         0,
         119
      ],
      "TagText":"JJ"
   },
   {
      "Font":"Classic",
      "userid":1112962991,
      "TagIdentification":" [ SIMP ] ",
      "ColorTable":[
         255,
         0,
         119
      ],
      "TagText":"Anti"
   },
   {
      "Font":"Classic",
      "userid":1685050142,
      "TagIdentification":" [ SIMP ] ",
      "ColorTable":[
         255,
         0,
         119
      ],
      "TagText":"0shmucks"
   },
   {
      "Font":"Classic",
      "userid":156756616,
      "TagIdentification":" [ TRYHARD WOMEN ] ",
      "ColorTable":[
         255,
         0,
         119
      ],
      "TagText":"Alizuuh"
   },
   {
      "Font":"Classic",
      "userid":1260243991,
      "TagIdentification":" [ TRYHARD WOMEN ] ",
      "ColorTable":[
         255,
         0,
         119
      ],
      "TagText":"gl8c"
   },
   {
      "Font":"Classic",
      "userid":41032892,
      "TagIdentification":" [ TRYHARD WOMEN ] ",
      "ColorTable":[
         255,
         0,
         119
      ],
      "TagText":"Kitncy"
   },
   {
      "Font":"Classic",
      "userid":114239440,
      "TagIdentification":" [ TRYHARD WOMEN ] ",
      "ColorTable":[
         255,
         0,
         119
      ],
      "TagText":"Kuiasii"
   },
   {
      "Font":"Classic",
      "userid":177990830,
      "TagIdentification":" [ AIMLOCKER TRYHARD ] ",
      "ColorTable":[
         255,
         0,
         119
      ],
      "TagText":"Zisukie"
   },
   {
      "Font":"Creepster",
      "userid":1186330995,
      "TagIdentification":" [ BOX HEAD ] ",
      "ColorTable":[
         255,
         255,
         0
      ],
      "TagText":"Rheapher"
   },
   {
      "Font":"Creepster",
      "userid":1977510288,
      "TagIdentification":" [ TOP 1 AFRICAN ] ",
      "ColorTable":[
         255,
         255,
         0
      ],
      "TagText":"Berhan"
   },
   {
      "Font":"Creepster",
      "userid":111994154,
      "TagIdentification":" [ SEX OFFENDER ] ",
      "ColorTable":[
         255,
         255,
         0
      ],
      "TagText":"Cherry"
   },
   {
      "Font":"Creepster",
      "userid":147387693,
      "TagIdentification":" [ TRYHARD ] ",
      "ColorTable":[
         0,
         255,
         0
      ],
      "TagText":"Demasaii"
   },
   {
      "Font":"Creepster",
      "userid":932528290,
      "TagIdentification":" [ TRYHARD ] ",
      "ColorTable":[
         0,
         255,
         0
      ],
      "TagText":"Do8m"
   },
   {
      "Font":"Creepster",
      "userid":1579693798,
      "TagIdentification":" [ TRYHARD ] ",
      "ColorTable":[
         0,
         255,
         0
      ],
      "TagText":"Remi"
   },
   {
      "Font":"Creepster",
      "userid":316508463,
      "TagIdentification":" [ TRYHARD / 'TOP 1' ] ",
      "ColorTable":[
         0,
         255,
         0
      ],
      "TagText":"Josh"
   },
   {
      "Font":"Creepster",
      "userid":971790374,
      "TagIdentification":" [ TOP 1 TRIM ] ",
      "ColorTable":[
         0,
         255,
         0
      ],
      "TagText":"Punk"
   },
   {
      "Font":"Creepster",
      "userid":"116974029",
      "TagIdentification":"[ RETARD ] ",
      "ColorTable":[
         255,
         0,
         0
      ],
      "TagText":"NOCONTEXT"
   },
   {
      "Font":"Creepster",
      "userid":"97483119",
      "TagIdentification":"[ SIMP ] ",
      "ColorTable":[
         255,
         0,
         119
      ],
      "TagText":"Michskii"
   },
   {
      "Font":"Classic",
      "userid":"147106532",
      "TagIdentification":"[ WEIRD ] ",
      "ColorTable":[
         255,
         69,
         156
      ],
      "TagText":"Shauns GF"
   },
   {
      "Font":"Classic",
      "userid":"542844700",
      "TagIdentification":"[ HOMOSEXUAL ] ",
      "ColorTable":[
         255,
         255,
         0
      ],
      "TagText":"Yuhxra"
   },
   {
      "Font":"Classic",
      "userid":"542844700",
      "TagIdentification":"[ TRYHARD ] ",
      "ColorTable":[
         0,
         255,
         0
      ],
      "TagText":"zatnz"
   }
]
