[
   {
      "Font":"Creepster",
      "userid":1898371630,
      "TagIdentification":" [ Scripter ] ",
      "ColorTable":[
         255,
         0,
         0
      ],
      "TagText":"Metacalled"
   },
   {
      "Font":"Creepster",
      "userid":463809410,
      "TagIdentification":" [ Velurity ] ",
      "ColorTable":[
         255,
         20,
         147
      ],
      "TagText":"Anna"
   },
   {
      "Font":"Creepster",
      "userid":668345977,
      "TagIdentification":" [ Aucestre ] ",
      "ColorTable":[
         0,
         0,
         0
      ],
      "TagText":"Eren"
   },
   {
      "Font":"Creepster",
      "userid":139759589,
      "TagIdentification":" [ Aucestre ] ",
      "ColorTable":[
         0,
         0,
         0
      ],
      "TagText":"Eren"
   },
   {
      "Font":"Creepster",
      "userid":2261302324,
      "TagIdentification":" [ Aucestre ] ",
      "ColorTable":[
         0,
         0,
         0
      ],
      "TagText":"Eren"
   },
   {
      "Font":"Creepster",
      "userid":1762590381,
      "TagIdentification":" [ Atuskiie ] ",
      "ColorTable":[
         255,
         20,
         147
      ],
      "TagText":"Kate"
   },
   {
      "Font":"Fredoka",
      "userid":147182208,
      "TagIdentification":" [ Retard Girl Group ] ",
      "ColorTable":[
         74,
         66,
         135
      ],
      "TagText":"Spudaddles"
   },
   {
      "Font":"Fredoka",
      "userid":1083587286,
      "TagIdentification":" [ Retard Girl Group ] ",
      "ColorTable":[
         74,
         66,
         135
      ],
      "TagText":"Jamie"
   },
   {
      "Font":"Fredoka",
      "userid":454243468,
      "TagIdentification":" [ Retard Girl Group ] ",
      "ColorTable":[
         74,
         66,
         135
      ],
      "TagText":"Shyanne"
   },
   {
      "Font":"Fredoka",
      "userid":192617749,
      "TagIdentification":" [ Retard Girl Group ] ",
      "ColorTable":[
         74,
         66,
         135
      ],
      "TagText":"Canan"
   },
   {
      "Font":"Fredoka",
      "userid":846150720,
      "TagIdentification":" [ Retard Girl Group ] ",
      "ColorTable":[
         74,
         66,
         135
      ],
      "TagText":"Jayda"
   },
   {
      "Font":"Fredoka",
      "userid":899010159,
      "TagIdentification":" [ Retard Girl Group ] ",
      "ColorTable":[
         74,
         66,
         135
      ],
      "TagText":"Jamie / Shyanne"
   },
   {
      "Font":"Creepster",
      "userid":1410480510,
      "TagIdentification":" [ Helper ] ",
      "ColorTable":[
         0,
         255,
         0
      ],
      "TagText":"Tester"
   },
   {
      "Font":"Creepster",
      "userid":1440862719,
      "TagIdentification":" [ Helper ] ",
      "ColorTable":[
         0,
         255,
         0
      ],
      "TagText":"Tester"
   },
   {
      "Font":"Creepster",
      "userid":713824573,
      "TagIdentification":" [ Scripter ] ",
      "ColorTable":[
         255,
         0,
         0
      ],
      "TagText":"Metacalled"
   },
   {
      "Font":"Creepster",
      "userid":105183043,
      "TagIdentification":" [ Scripter ] ",
      "ColorTable":[
         20,
         247,
         244
      ],
      "TagText":"Charlie"
   },
   {
      "Font":"Creepster",
      "userid":1762400000,
      "TagIdentification":" [ Passaround ] ",
      "ColorTable":[
         74,
         66,
         135
      ],
      "TagText":"KD"
   },
   {
      "Font":"Creepster",
      "userid":92616350,
      "TagIdentification":" [ Passaround ] ",
      "ColorTable":[
         74,
         66,
         135
      ],
      "TagText":"Libby"
   },
   {
      "Font":"Creepster",
      "userid":781004960,
      "TagIdentification":" [ Passaround ] ",
      "ColorTable":[
         74,
         66,
         135
      ],
      "TagText":"Zoe"
   },
   {
      "Font":"Creepster",
      "userid":1006384408,
      "TagIdentification":" [ COOL ] ",
      "ColorTable":[
         0,
         255,
         255
      ],
      "TagText":"updtd"
   },
   {
      "Font":"Creepster",
      "userid":20165690,
      "TagIdentification":" [ COOL ] ",
      "ColorTable":[
         0,
         255,
         255
      ],
      "TagText":"Shaun"
   },
   {
      "Font":"Creepster",
      "userid":1417460726,
      "TagIdentification":" [ COOL ] ",
      "ColorTable":[
         0,
         255,
         255
      ],
      "TagText":"Fergo"
   }
]
