[
   {
      "Font":"Creepster",
      "userid":1898371630,
      "Color":"Red",
      "TagIdentification":"SC",
      "TagText":"Metacalled"
   },
   {
      "Font":"Creepster",
      "userid":713824573,
      "Color":"Red",
      "TagIdentification":"SC",
      "TagText":"Metacalled"
   },
   {
      "Font":"Creepster",
      "userid":463809410,
      "Color":"Pink",
      "TagIdentification":"Custom/VELURITY",
      "TagText":"Anna"
   },
   {
      "Font":"Creepster",
      "userid":668345977,
      "Color":"Purple",
      "TagIdentification":"Custom/AUCESTRE",
      "TagText":"Eren"
   },
   {
      "Font":"Creepster",
      "userid":139759589,
      "Color":"Purple",
      "TagIdentification":"Custom/AUCESTRE",
      "TagText":"Eren"
   },
   {
      "Font":"Creepster",
      "userid":2261302324,
      "Color":"Purple",
      "TagIdentification":"Custom/AUCESTRE",
      "TagText":"Eren"
   },
   {
      "Font":"Creepster",
      "userid":1762590381,
      "Color":"RedPink",
      "TagIdentification":"Custom/BITCH",
      "TagText":"Kate"
   },
   {
      "Font":"Fredoka",
      "userid":147182208,
      "Color":"Grl",
      "TagIdentification":"Custom/RETARD GIRL GROUP",
      "TagText":"Spudaddles"
   },
   {
      "Font":"Fredoka",
      "userid":1083587286,
      "Color":"Grl",
      "TagIdentification":"Custom/RETARD GIRL GROUP",
      "TagText":"Jamie"
   },
   {
      "Font":"Fredoka",
      "userid":454243468,
      "Color":"Grl",
      "TagIdentification":"Custom/RETARD GIRL GROUP",
      "TagText":"Shyanne"
   },
   {
      "Font":"Fredoka",
      "userid":192617749,
      "Color":"Grl",
      "TagIdentification":"Custom/RETARD GIRL GROUP",
      "TagText":"Canan"
   },
   {
      "Font":"Fredoka",
      "userid":846150720,
      "Color":"Grl",
      "TagIdentification":"Custom/RETARD GIRL GROUP",
      "TagText":"Jayda"
   },
   {
      "Font":"Fredoka",
      "userid":899010159,
      "Color":"Grl",
      "TagIdentification":"Custom/RETARD GIRL GROUP",
      "TagText":"Jamie / Shyanne"
   },
   {
      "Font":"Creepster",
      "userid":1762400000,
      "Color":"Grl",
      "TagIdentification":"Custom/PASSAROUND",
      "TagText":"KD"
   },
   {
      "Font":"Creepster",
      "userid":92616350,
      "Color":"Grl",
      "TagIdentification":"Custom/PASSAROUND",
      "TagText":"Libby"
   },
   {
      "Font":"Creepster",
      "userid":781004960,
      "Color":"Grl",
      "TagIdentification":"Custom/PASSAROUND",
      "TagText":"Zoe"
   },
   {
      "Font":"Creepster",
      "userid":2258301745,
      "Color":"Grl",
      "TagIdentification":"Custom/PASSAROUND",
      "TagText":"Kim"
   },
   {
      "Font":"Creepster",
      "userid":1410480510,
      "Color":"Green",
      "TagIdentification":"Custom/HELPER",
      "TagText":"Alex"
   },
   {
      "Font":"Creepster",
      "userid":1440862719,
      "Color":"Green",
      "TagIdentification":"Custom/HELPER",
      "TagText":"Alexr"
   },
   {
      "Font":"Creepster",
      "userid":105183043,
      "Color":[
         20,
         247,
         244
      ],
      "TagIdentification":"SC",
      "TagText":"Charlie"
   },
   {
      "Font":"Creepster",
      "userid":20165690,
      "Color":[
         0,
         255,
         255
      ],
      "TagIdentification":"CO",
      "TagText":"Shaun"
   },
   {
      "Font":"Creepster",
      "userid":1417460726,
      "Color":[
         0,
         255,
         255
      ],
      "TagIdentification":"CO",
      "TagText":"Fergo"
   },
   {
      "Font":"Creepster",
      "userid":1006384408,
      "Color":[
         0,
         255,
         255
      ],
      "TagIdentification":"CO",
      "TagText":"Updtd"
   },
   {
      "Font":"Creepster",
      "userid":24158945,
      "Color":[
         0,
         255,
         255
      ],
      "TagIdentification":"CO",
      "TagText":"Scottish"
   },
   {
      "Font":"Creepster",
      "userid":94428247,
      "Color":[
         0,
         255,
         255
      ],
      "TagIdentification":"CO",
      "TagText":"Charlotte"
   },
   {
      "Font":"Fredoka",
      "userid":1937111826,
      "Color":"Red",
      "TagIdentification":"RE",
      "TagText":"SlayesXl"
   },
   {
      "Font":"Fredoka",
      "userid":221789271,
      "Color":"Red",
      "TagIdentification":"RE",
      "TagText":"Townley"
   },
   {
      "Font":"Fredoka",
      "userid":1578148497,
      "Color":"Red",
      "TagIdentification":"RE",
      "TagText":"Townley ( SHARED )"
   },
   {
      "Font":"Bangers",
      "userid":355053032,
      "Color":"RedPink",
      "TagIdentification":"Custom/FANBOY",
      "TagText":"gohnmane"
   },
   {
      "Font":"Classic",
      "userid":1506101592,
      "Color":"RedPink",
      "TagIdentification":"SMP",
      "TagText":"c6pl"
   },
   {
      "Font":"Classic",
      "userid":75838249,
      "Color":"RedPink",
      "TagIdentification":"SMP",
      "TagText":"JJ"
   },
   {
      "Font":"Classic",
      "userid":1112962991,
      "Color":"RedPink",
      "TagIdentification":"SMP",
      "TagText":"Anti"
   },
   {
      "Font":"Classic",
      "userid":1685050142,
      "Color":"RedPink",
      "TagIdentification":"SMP",
      "TagText":"0shmucks"
   },
   {
      "Font":"Classic",
      "userid":156756616,
      "Color":"RedPink",
      "TagIdentification":"Custom/TRYHARD WOMEN",
      "TagText":"Alizuuh"
   },
   {
      "Font":"Classic",
      "userid":1260243991,
      "Color":"RedPink",
      "TagIdentification":"Custom/TRYHARD WOMEN",
      "TagText":"gl8c"
   },
   {
      "Font":"Classic",
      "userid":41032892,
      "Color":"RedPink",
      "TagIdentification":"Custom/TRYHARD WOMEN",
      "TagText":"Kitncy"
   },
   {
      "Font":"Classic",
      "userid":114239440,
      "Color":"RedPink",
      "TagIdentification":"Custom/TRYHARD WOMEN",
      "TagText":"Kuiasii"
   },
   {
      "Font":"Classic",
      "userid":177990830,
      "Color":"RedPink",
      "TagIdentification":"Custom/AIMLOCKER TRYHARD",
      "TagText":"Zisukie"
   },
   {
      "Font":"Creepster",
      "userid":1186330995,
      "Color":"Yellow",
      "TagIdentification":"Custom/BOX HEAD",
      "TagText":"Rheapher"
   },
   {
      "Font":"Creepster",
      "userid":1977510288,
      "Color":"Yellow",
      "TagIdentification":"Custom/TOP 1 AFRICAN",
      "TagText":"Berhan"
   },
   {
      "Font":"Creepster",
      "userid":111994154,
      "Color":"Yellow",
      "TagIdentification":"Custom/SEX OFFENDER",
      "TagText":"Cherry"
   },
   {
      "Font":"Creepster",
      "userid":147387693,
      "Color":"Green",
      "TagIdentification":"TR",
      "TagText":"Demasaii"
   },
   {
      "Font":"Creepster",
      "userid":932528290,
      "Color":"Green",
      "TagIdentification":"TR",
      "TagText":"Do8m"
   },
   {
      "Font":"Creepster",
      "userid":1579693798,
      "Color":"Green",
      "TagIdentification":"TR",
      "TagText":"Remi"
   },
   {
      "Font":"Creepster",
      "userid":316508463,
      "Color":"Green",
      "TagIdentification":"Custom/TRYHARD 'TOP 1'",
      "TagText":"Josh"
   },
   {
      "Font":"Creepster",
      "userid":971790374,
      "Color":"Green",
      "TagIdentification":"Custom/TOP 1 TRIM",
      "TagText":"Punk"
   }
]
